# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Unity Mac Agents
  demands: Unity_2022




steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UnityBuildTask@3
  inputs:
    buildTarget: 'standalone'
    versionSelectionMode: 'specify'
    version: '2022.3.17f1'
    outputPath: '$(Build.BinariesDirectory)'
    outputFileName: 'drop'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
